// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnme-cckxR7brjCccFvLorhZzIX68RKsc',
    appId: '1:201127488522:web:5459e0f14368fb8fc9c3f3',
    messagingSenderId: '201127488522',
    projectId: 'foodhub-5e36a',
    authDomain: 'foodhub-5e36a.firebaseapp.com',
    storageBucket: 'foodhub-5e36a.firebasestorage.app',
    measurementId: 'G-LY4CX5VV7J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjSqmJdQJxyvvdPIRtlRL8XWN4EbTF2tE',
    appId: '1:201127488522:android:48fcb797956ece16c9c3f3',
    messagingSenderId: '201127488522',
    projectId: 'foodhub-5e36a',
    storageBucket: 'foodhub-5e36a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxN-rG2LGha7mwwrSi6TuR-bT4lrYZSC0',
    appId: '1:201127488522:ios:ab95372980082944c9c3f3',
    messagingSenderId: '201127488522',
    projectId: 'foodhub-5e36a',
    storageBucket: 'foodhub-5e36a.firebasestorage.app',
    iosClientId:
        '201127488522-f5eh4btdonjqdfhnh555mnba47h2pin1.apps.googleusercontent.com',
    iosBundleId: 'com.alimad.foodhub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxN-rG2LGha7mwwrSi6TuR-bT4lrYZSC0',
    appId: '1:201127488522:ios:503cdf0fffc7fcdcc9c3f3',
    messagingSenderId: '201127488522',
    projectId: 'foodhub-5e36a',
    storageBucket: 'foodhub-5e36a.firebasestorage.app',
    iosClientId:
        '201127488522-spvtgnhb44u1p2e9d2qc3ausbqgff08u.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBnme-cckxR7brjCccFvLorhZzIX68RKsc',
    appId: '1:201127488522:web:5c6f56aef32ac8aec9c3f3',
    messagingSenderId: '201127488522',
    projectId: 'foodhub-5e36a',
    authDomain: 'foodhub-5e36a.firebaseapp.com',
    storageBucket: 'foodhub-5e36a.firebasestorage.app',
    measurementId: 'G-76R6XRKSXZ',
  );
}
